/**
 * Reverence pre-filter — P0 safety surface (Durable rule #1).
 *
 * On any closed-door signal we stop that topic/person/period permanently with
 * one gentle acknowledgment and never re-approach. This filter runs
 * DETERMINISTICALLY on every subscriber turn BEFORE the turn ever reaches
 * Claude, so a closed door stays closed even if Claude misbehaves or omits a
 * structured payload.
 *
 * Keep this simple and auditable: plain normalized-substring / regex matching
 * on explicit closed-door phrases. No model, no fuzzy scoring. Every match
 * records the phrase that triggered it so the closure is fully auditable
 * (adversarial QA ship gate).
 *
 * This is intentionally a HIGH-PRECISION list of explicit refusals. It is a
 * floor, not the whole reverence system — Claude is still instructed to honor
 * subtler closed-door cues. The deterministic floor exists so the most explicit
 * signals can never slip through.
 */

export interface ReverenceMatch {
  /** The exact closed-door phrase (canonical form) that matched. */
  phrase: string;
  /** The matched substring as it appeared in the subscriber's utterance. */
  matchedText: string;
}

/**
 * Canonical closed-door phrases. Matched case-insensitively against a
 * whitespace-normalized, punctuation-stripped form of the utterance, so
 * "I'd rather not." and "id rather not" both match "i'd rather not".
 *
 * Ordering: longer/more-specific phrases first so the recorded match is the
 * most informative one.
 */
export const CLOSED_DOOR_PHRASES: readonly string[] = [
  "i don't want to talk about",
  "i do not want to talk about",
  "i don't want to talk about that",
  "i don't want to get into",
  "i don't want to answer",
  "i do not want to answer",
  "i don't want to go there",
  "i don't want to discuss",
  "please stop talking about",
  "stop talking about",
  "stop asking about",
  "stop asking me about",
  "can we not talk about",
  "let's not talk about",
  "let us not talk about",
  "i'd rather not talk about",
  "i'd rather not get into",
  "i'd rather not answer",
  "i'd rather not",
  "i would rather not",
  "i'd prefer not to",
  "i would prefer not to",
  "i don't want to go into",
  "rather not say",
  "i'd rather not say",
  "leave it alone",
  "drop it",
  "let it go",
  "not going to talk about",
  "i'm not going to talk about",
  "i won't talk about",
  "i will not talk about",
  "skip this",
  "skip that",
  "let's skip",
  "let's move on",
  "can we move on",
  "move on please",
  "next question",
  "no comment",
  "that's private",
  "that is private",
  "that's none of your business",
  "none of your business",
  "not your business",
  "i don't wish to discuss",
];

/**
 * Normalize an utterance for matching:
 * - lowercase
 * - convert curly apostrophes to straight
 * - strip punctuation except apostrophes (so "don't" stays intact)
 * - collapse whitespace
 */
export function normalizeForReverence(text: string): string {
  return text
    .toLowerCase()
    .replace(/[‘’ʼ]/g, "'")
    .replace(/[^a-z0-9'\s]/g, ' ')
    .replace(/\s+/g, ' ')
    .trim();
}

/**
 * Returns the first closed-door match in the subscriber utterance, or null.
 * Phrases are also matched in an apostrophe-stripped form so "id rather not"
 * (a common STT rendering) still trips.
 */
export function detectClosedDoor(utterance: string): ReverenceMatch | null {
  if (!utterance) return null;
  const normalized = normalizeForReverence(utterance);
  const normalizedNoApostrophe = normalized.replace(/'/g, '');

  for (const phrase of CLOSED_DOOR_PHRASES) {
    const needle = phrase;
    const needleNoApostrophe = phrase.replace(/'/g, '');
    if (normalized.includes(needle)) {
      return { phrase, matchedText: needle };
    }
    if (needleNoApostrophe !== needle && normalizedNoApostrophe.includes(needleNoApostrophe)) {
      return { phrase, matchedText: needleNoApostrophe };
    }
  }
  return null;
}

/**
 * The single gentle acknowledgment Seth speaks when a door closes. Deliberately
 * short, warm, and final — it does not probe, does not re-approach, and signals
 * we are moving on. This is the system-level intervention text that OVERRIDES
 * Claude's next prompt; it is spoken verbatim by Hume and never generated by
 * the model on this path.
 */
export const REVERENCE_ACKNOWLEDGMENT =
  "Of course — we'll leave that there. Thank you for telling me. Let's go somewhere else whenever you're ready.";
